apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-app
  namespace: frontend
spec:
  selector:
    matchLabels:
      app: frontend-app
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend-app
    spec:
      containers:
      - name: frontend-app
        image: gcr.io/central-rush-424822-a5/frontendapp:latest

        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred